version: '3'

services:
        php:
                build:
                      context: .
                      dockerfile: Dockerfile
                ports:
                        -  3000:80
                depends_on: 
                        - "db"
                volumes:
                        - ./docker/www:/var/www/html

        db:
                image: mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: root
                volumes: 
                        - ./docker/db:/var/lib/mysql
        adminer:
            image: adminer
            ports:
              - 8080:8080
        
       